---
- hosts: dns
  sudo: true
  tasks:
    - name: install pdns
      yum:
        name: pdns, pdns-backend-mysql
        state: latest
    - name: changing local address
      lineinfile:
        path: /etc/pdns/pdns.conf
        regexp: '^# local-address'
        line: 'local-address=127.0.0.1'
    - name: changing local address
      lineinfile:
        path: /etc/pdns/pdns.conf
        regexp: '^# local-port'
        line: 'local-port=5300'
    - name: changing lauch
      lineinfile:
        path: /etc/pdns/pdns.conf
        regexp: '^launch=bind'
        line: 'launch=gmysql'
    - name: adding host
      lineinfile:
        path: /etc/pdns/pdns.conf
        line: 'gmysql-host=192.168.200.2'
        insertafter: '^launch=gmysql'
    - name: adding user
      lineinfile:
        path: /etc/pdns/pdns.conf
        line: 'gmysql-user=powerdns'
        insertafter: '^gmysql-host=192.168.200.2'
    - name: adding password
      lineinfile:
        path: /etc/pdns/pdns.conf
        line: 'gmysql-password=heslo'
        insertafter: '^gmysql-user=powerdns'
    - name: adding dbname
      lineinfile:
        path: /etc/pdns/pdns.conf
        line: 'gmysql-dbname=powerdns'
        insertafter: '^gmysql-password=heslo'
    - name: start the pdns service
      service: 
        name: pdns
        state: started
        enabled: true
    - name: add zone
      command: pdnsutil create-zone vagrantjeblbost.net private.vagrantjeblbost.net
    - name: add record
      command: pdnsutil add-record vagrantjeblbost.net private A 192.168.200.2
    - name: add zone
      command: pdnsutil create-zone net nenavidimsvujzivot.net
    - name: add record
      command: pdnsutil add-record net nenavidimsvujzivot A 192.168.200.2
    - name: install recursor
      yum:
        name: pdns-recursor
        state: latest
    - name: change allow from
      lineinfile:
        path: /etc/pdns-recursor/recursor.conf
        regexp: '^# allow-from='
        line: 'allow-from=127.0.0.0/8, 192.168.200.0/24'
    - name: change local address
      lineinfile:
        path: /etc/pdns-recursor/recursor.conf
        regexp: '^# local-address'
        line: 'local-address=192.168.200.3'
    - name: change local port
      lineinfile:
        path: /etc/pdns-recursor/recursor.conf
        regexp: '^# local-port='
        line: 'local-port=53'
    - name: adding forward zone
      lineinfile:
        path: /etc/pdns-recursor/recursor.conf
        regexp: '^# forward-zones='
        line: 'forward-zones=private.vagrantjeblbost.net=127.0.0.1:5300, nenavidimsvujzivot.net=127.0.0.1:5300'
    - name: start recursor
      service:
        name: pdns-recursor
        state: started
        enabled: true