---
- hosts: sql
  sudo: true
  tasks:
    - name: Install maria
      yum:
        name: mariadb-server, mariadb
        state: latest
    - name: Start the mariadb service
      service: 
        name: mariadb
        state: started
        enabled: true
    - name: Restart the service
      service:
        name: mariadb
        state: restarted